In [1]:
!pip install transformers
!pip install tensorflow
!pip install torch

     |████████████████████████████████| 3.8 MB 24.3 MB/s 
     |████████████████████████████████| 6.5 MB 29.5 MB/s 
     |████████████████████████████████| 895 kB 50.3 MB/s 
     |████████████████████████████████| 67 kB 6.1 MB/s 
     |████████████████████████████████| 596 kB 56.0 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13
     |████████████████████████████████| 462 kB 29.6 MB/s 


In [2]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from transformers import pipeline
import tensorflow as tf
import torch
import numpy as np

In [3]:
def new_softmax(a) : 
    c = np.max(a) # 최댓값
    exp_a = np.exp(a-c) # 각각의 원소에 최댓값을 뺀 값에 exp를 취한다. (이를 통해 overflow 방지)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    return y

In [4]:
model_name = "snunlp/KR-FinBert-SC"

In [5]:
tokenizer = AutoTokenizer.from_pretrained("snunlp/KR-FinBert-SC")
model = AutoModelForSequenceClassification.from_pretrained("snunlp/KR-FinBert-SC")

Downloading:   0%|          | 0.00/372 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/140k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/287k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/112 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/881 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/387M [00:00<?, ?B/s]

In [6]:
classifier = pipeline("feature-extraction", model=model, tokenizer=tokenizer)

In [7]:
new_softmax(classifier("부품 공급 차질에…기아차 광주공장 전면 가동 중단")) # 부정적 뉴스 # (부정확률,중립확률,긍정확률) (합하면 1)

array([[9.99787783e-01, 1.40736038e-04, 7.14806357e-05]])

In [8]:
new_softmax(classifier("박문덕 하이트진로 회장 호시우행으로 100년 기업 준비")) # 중립적 뉴스

array([[3.53520207e-05, 9.99876474e-01, 8.81736269e-05]])

In [9]:
new_softmax(classifier("하이트진로, 1분기 영업익 262억…전년비 148% 상승")) # 긍정적 뉴스

array([[4.23487052e-05, 7.95004343e-05, 9.99878151e-01]])

In [2]:
classifier2 = pipeline("text-classification", model=model, tokenizer=tokenizer)  # 부정,중립,긍정 확률을 계산한 후 가장 확률이 큰 쪽으로 분류하고 그 확률을 스코어로 출력

NameError: name 'pipeline' is not defined

In [1]:
classifier2("대림산업, 인천 'e편한세상 서창' 분양")

NameError: name 'classifier2' is not defined

In [ ]:
example_dataset = ["현대바이오, '폴리탁셀' 코로나19 치료 가능성에 19% 급등", "영화관株 '코로나 빙하기' 언제 끝나나…CJ CGV 올 4000억 손실 날수도", "이수화학, 3분기 영업익 176억…전년比 80%↑",
               "C쇼크에 멈춘 흑자비행…대한항공 1분기 영업적자 566억", "GKL, 7년 만에 두 자릿수 매출성장 예상", "1000억대 횡령·배임' 최신원 회장 구속… SK네트웍스 경영 공백 방지 최선",
               "위지윅스튜디오, 콘텐츠 활약에 사상 첫 매출 1000억원 돌파", "부품 공급 차질에…기아차 광주공장 전면 가동 중단",
               "삼성전자, 2년 만에 인도 스마트폰 시장 점유율 1위 '왕좌 탈환'", "현대제철, 지난해 영업익 3,313억원···전년比 67.7% 감소"]

In [ ]:
for sentence in example_dataset:
  print(sentence, classifier(sentence))

현대바이오, '폴리탁셀' 코로나19 치료 가능성에 19% 급등 [{'label': 'positive', 'score': 0.9998695850372314}]
영화관株 '코로나 빙하기' 언제 끝나나…CJ CGV 올 4000억 손실 날수도 [{'label': 'negative', 'score': 0.9998133778572083}]
이수화학, 3분기 영업익 176억…전년比 80%↑ [{'label': 'positive', 'score': 0.9807855486869812}]
C쇼크에 멈춘 흑자비행…대한항공 1분기 영업적자 566억 [{'label': 'negative', 'score': 0.9998134970664978}]
GKL, 7년 만에 두 자릿수 매출성장 예상 [{'label': 'positive', 'score': 0.9998507499694824}]
1000억대 횡령·배임' 최신원 회장 구속… SK네트웍스 경영 공백 방지 최선 [{'label': 'negative', 'score': 0.9996323585510254}]
위지윅스튜디오, 콘텐츠 활약에 사상 첫 매출 1000억원 돌파 [{'label': 'positive', 'score': 0.9998825788497925}]
부품 공급 차질에…기아차 광주공장 전면 가동 중단 [{'label': 'negative', 'score': 0.9997877478599548}]
삼성전자, 2년 만에 인도 스마트폰 시장 점유율 1위 '왕좌 탈환' [{'label': 'positive', 'score': 0.9998806715011597}]
현대제철, 지난해 영업익 3,313억원···전년比 67.7% 감소 [{'label': 'negative', 'score': 0.9998225569725037}]
